# Generated by Django 4.0.6 on 2022-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='shipping address', max_length=500, null=True, verbose_name='address'),
        ),
    ]
