# Generated by Django 4.1.7 on 2023-03-30 05:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart_id', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='customer name', max_length=250, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='name')),
                ('email', models.EmailField(help_text='used for feedback', max_length=254, verbose_name='email')),
                ('phone', models.CharField(help_text='used for feedback', max_length=13, validators=[django.core.validators.RegexValidator(message='The phone number must be in the format: "+380999999999". Starts with "+380" and 9 digits.', regex='^\\+380\\d{9}')], verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False, help_text='order dispatch status', verbose_name='sent')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='total price of order', max_digits=12, verbose_name='total price')),
                ('customer', models.ForeignKey(help_text='communication with the Customer model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='the quantity of the product in the cart item', verbose_name='quantity')),
                ('active', models.BooleanField(default=True, help_text='indicator of the state of the cart item', verbose_name='active')),
                ('sub_total', models.DecimalField(decimal_places=2, help_text='the total price of the products in cart item', max_digits=12, verbose_name='total price')),
                ('cart', models.ForeignKey(blank=True, help_text='communication with the Cart model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart', verbose_name='cart')),
                ('order', models.ForeignKey(blank=True, help_text='communication with the Order model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order', verbose_name='order')),
                ('product', models.ForeignKey(help_text='communication with the Product model', on_delete=django.db.models.deletion.CASCADE, to='flower.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'cart item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
