# Generated by Django 4.1.7 on 2023-04-01 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flower', '0004_product_number_of_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='name of recommendation', max_length=250, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('active', models.BooleanField(default=True, help_text='active recommendation or not', verbose_name='active')),
                ('product', models.ManyToManyField(help_text='products in the recommendation', to='flower.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-created'],
            },
        ),
    ]
