# Generated by Django 4.1.7 on 2023-03-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_category_alter_product_price_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='the price of the product in coins', verbose_name='price'),
        ),
    ]
