# Generated by Django 4.1.7 on 2023-04-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sold',
            field=models.PositiveIntegerField(default=0, help_text='the number of sold products', verbose_name='number of sold'),
        ),
    ]
